export const environment = {
  production: false,
  aiInstrumentationKey: 'db116377-6a23-4d6a-945b-38af84a8db0e',
  auth0Audience: 'https://cloudskew-test/api',
  auth0ClientId: 'qAzxIE6cfPdMk6JIzVgn6S966uyGH7SO',
  auth0Domain: 'cloudskew-test.auth0.com',
  auth0LogoutUrl: 'https://cloudskewlandingtest.azureedge.net',
  auth0RedirectUri: 'https://cloudskewuitest.azureedge.net/authcallback',
  cdnUrlPrefix: 'https://cloudskewtest.azureedge.net',
  customImagesUrlPrefix: 'https://cloudskewcustomimagestest.azureedge.net',
  diagramHelperWebAPIUrl: 'https://cloudskewtest.azure-api.net/cloudskewfunctionstest',
  diagramShareUrl: 'https://cloudskewuitest.azureedge.net/viewer',
  docsUrl: 'https://cloudskewdocstest.azureedge.net',
  professionalPriceId: 'price_1HtWGaKGaI8j1MzviNzbVlQR',
  stripeAPIPublishableKey: 'pk_test_51HsQNnKGaI8j1Mzv7S771QodfMDqx7GWcMekH0U4Hz3prTaIIwCVbKuPVCA3ufyKfJjDLh9xhd7GopGzpqqr60X000RM9w8hH0',
  stripeCheckoutSessionCancelUrl: 'https://cloudskewuitest.azureedge.net',
  stripeCheckoutSessionSuccessUrl: 'https://cloudskewuitest.azureedge.net/checkoutsessioncallback/{CHECKOUT_SESSION_ID}',
  stripeCustomerPortalReturnUrl: 'https://cloudskewuitest.azureedge.net',
  webAPIPublicUrl: 'https://cloudskewtest.azure-api.net/cloudskewfunctionstest-public',
  webAPIUrl: 'https://cloudskewtest.azure-api.net/cloudskewfunctionstest',
};
