export const environment = {
  production: true,
  aiInstrumentationKey: 'bd71c98e-47fc-4e3b-9a38-5b01b705776c',
  auth0Audience: 'https://cloudskew/api',
  auth0ClientId: 'Vt56J1J0WcVvXRt3zqjBzzRmMQvzrh1r',
  auth0Domain: 'cloudskew.auth0.com',
  auth0LogoutUrl: 'https://www.cloudskew.com',
  auth0RedirectUri: 'https://app.cloudskew.com/authcallback',
  cdnUrlPrefix: 'https://assets.cloudskew.com',
  customImagesUrlPrefix: 'https://customimages.cloudskew.com',
  diagramHelperWebAPIUrl: 'https://cloudskewprod.azure-api.net/cloudskewfunctionsprod',
  diagramShareUrl: 'https://app.cloudskew.com/viewer',
  docsUrl: 'https://docs.cloudskew.com',
  professionalPriceId: 'price_1Hz1K2KGaI8j1Mzv73Od0sqs',
  stripeAPIPublishableKey: 'pk_live_51HsQNnKGaI8j1MzvgQ6Ouvq89xxixPyeIy5dswB1RQvlN05r8wlWHGimIJhGznUCl6FJR3nLkieNIKh8meGS0DyV00E5cKrkha',
  stripeCheckoutSessionCancelUrl: 'https://app.cloudskew.com',
  stripeCheckoutSessionSuccessUrl: 'https://app.cloudskew.com/checkoutsessioncallback/{CHECKOUT_SESSION_ID}',
  stripeCustomerPortalReturnUrl: 'https://app.cloudskew.com',
  webAPIPublicUrl: 'https://cloudskewprod.azure-api.net/cloudskewfunctionsprod-public',
  webAPIUrl: 'https://cloudskewprod.azure-api.net/cloudskewfunctionsprod',
};
